### ISSUE TITLE
Automate HGVS generation

### ISSUE THREAD

**Issue by acoffman** [griffithlab/civic-server#143]
When we have fully populated variant coordinates, automatically generate the HGVS for a variant.

**Comment by acoffman** [comment]
This is potentially needed for linking to various other sources of variant information (ClinVar, MyVariantInfo, etc)

**Comment by obigriffith** [comment]
I don't think we should wait for fully populated variant coordinates to do this. A question to address, does HGVS become a variant synonym or is it a separate field? Do we support multiple HGVS strings per variant?

**Comment by malachig** [comment]
I think it would be desirable to have multiple HGVS values for each variant (because several are equally valid). They could be stored as synonyms.

Perhaps we should have some (optional) metadata associated with each synonym. e.g. synonym type (of which one option could be 'hgvs')?

Alternatively we could handle hgvs separately from other synonyms.

In some cases there will be *many* valid hgvs values for a particular CIViC variant. e.g. for 'MUTATION' variants.  Also note that some hgvs strings a genome build context dependent.

**Comment by malachig** [comment]
To facilitate integration with ClinVar, perhaps we should directly emulate their approach to hgvs.

**Comment by malachig** [comment]
Example from ClinVar for a simple missense mutation in EGFR:

<img width="826" alt="clinvar example" src="https://cloud.githubusercontent.com/assets/856728/18483768/2f7a18f4-79ab-11e6-93dc-95faa1e521b7.png">

**Comment by acoffman** [comment]
Start with genomic HGVS, make each one a suggested change. Then move on to ENST.

**Comment by malachig** [comment]
We now support adding multiple HGVS expressions.  But this is still very manual.  A future solution to this problem might be to try to associate each CIViC variant with a ClinGen Allele Registry ID (possibly making this connection from one manually determined HGVS) and then simply leveraging the Allele Registry to get additional equivalent HGVS expression for the variant.

**Comment by kkrysiak** [comment]
Rather than creating the same civicbot curation effort, this would be better served by connecting to the ClinGen Allele Registry that we already connect to. https://github.com/griffithlab/civic-server/issues/363
