### ISSUE TITLE
Scrape Clinical Trial ID from PubMed if it exists

### ISSUE THREAD

**Issue by acoffman** [griffithlab/civic-server#334]
Example: https://www.ncbi.nlm.nih.gov/pubmed/27959700 (secondary source id)

**Comment by acoffman** [comment]
Support for this now exists. Next I need to add it to the response objects in the API so that @jmcmichael can add it to the views.

**Comment by susannasiebert** [comment]
I'm taking a stab at this since it seems pretty straightforward. In the latest data dump I see three clinical trials but none of them seem to be linked to a source. I see that `lib/scrapers/pub_med.rb` is supposed to make that association. Does line 49 need to be `source.clinical_trials < clinical_trials`? Maybe that line needs to move inside of the loop to assign one at a time?

Do we also need to backfill existing sources? If I interpret the code correctly, it looks like the scraper only works on new sources.

**Comment by susannasiebert** [comment]
Ok, strike that. The bridge entries do exist but for some reason my local database doesn't have the corresponding source entries. The sources exist on the live db.
