### ISSUE TITLE
Admin evidence item move leaves evidence in conflicted state

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/civic-server#339]
Schrodinger's Evidence:

![image](https://user-images.githubusercontent.com/811065/27927054-16cb5c08-6250-11e7-8db6-e27df640a059.png)

Caused by rejected item -> admin moved item to new variant name -> accepted item

**Comment by acoffman** [comment]
@ahwagner Yeah, this would occur without the move too. Its currently intentional as it represents the actual history of the EID though we should definitely indicate more clearly what the _current_ status is.

I don't know that we'd want to hide the fact that it had been previously rejected though. What do you think?

**Comment by ahwagner** [comment]
I think that at any given time evidence can only be accepted OR rejected. When displaying these tags at the top of the evidence record, this should be reflected by showing only the most recently applied of two tags.

What do others think?

**Comment by acoffman** [comment]
So, by way of explanation; that is currently true - an EID has a status, which can only hold a single value at a time. Whats displayed on top however isn't the status, its the list of "lifecycle events" for that entity in chronological order. So all of those events did happen and were recorded, which is why they're displayed. But perhaps the display is misleading?

**Comment by jmcmichael** [comment]
The only thing wrong with this display, IMO, is that the accepted/rejected sequence is out of order. If it were ordered Submitted, Rejected, Accepted then it would be correct and actually correspond to what happened. I'd prefer to keep all the lifecycle events, but order them properly.

**Comment by ahwagner** [comment]
Ah, I understand. That isn't clear to me when I look at the display--I expect that this type of history is what the EID Log is for, and that the tags at the top only show the key milestones of that history. If the tags on top are the lifecycle events, does that mean that (when ordered chronologically) a subsequent rejection would make it look like `rejected by`-> `accepted by` -> `rejected by`?

**Comment by jmcmichael** [comment]
I think so, yeah. At any rate the loop displaying those action blocks ignores the timestamps provided, so I'm going to fix that. Then at least they'll be properly ordered.

**Comment by obigriffith** [comment]
I think I agree that this should be more milestone based. In my mind the attribution for evidence items should be:
1. submitted by
2. accepted by OR rejected by - only for *current* status.
3. last modified by
4. last reviewed by
5. last commented by
