### ISSUE TITLE
Handle API requests using gene symbols that contain slashes

### ISSUE THREAD

**Issue by oplantalech** [griffithlab/civic-server#361]
Currently, API requests using gene symbols that contain slashes return an error. For instance, for the gene MIR-1280/1280: https://civic.genome.wustl.edu/api/genes/MIR-1280%2F1280?identifier_type=entrez_symbol

This happen because Apache interprets an url-escaped slash (`%2F`)  as a `/` and breaks the route. It can be fixed by switching on the AllowEncodedSlashes directive in Apache (by default it's switched off).

**Comment by acoffman** [comment]
Hi @oplantalech,

Thanks for the report! This should be fixed in the next deploy of the site. The router will now interpret the slash correctly and search for the expected entrez gene symbol. I tested your specific query and it looks like, unfortunately, we don't have any evidence records for that particular gene, so you will get a "404", but the behavior is now expected/correct.

Thanks again for your interest in CIViC!
