### ISSUE TITLE
Allele registry ID issue

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-server#418]
Not sure what has gone wrong here. <img width="1133" alt="screen shot 2018-03-11 at 4 02 29 pm" src="https://user-images.githubusercontent.com/8527125/37258421-c69022c8-2545-11e8-8568-2084a3758dd6.png">

**Comment by susannasiebert** [comment]
I don't see this same issue. This is the correct variant, right? https://civicdb.org/events/genes/58/summary/variants/1816/summary#variant

**Comment by susannasiebert** [comment]
I think there might be an issue with the allele registry API/server. This is the url it's trying to hit `http://reg.genome.network/allele?hgvs=NC_000003.11:g.10183745del` and it's hanging for me. We pull in the allele registry id at runtime, which is why the return is different for me. We should probably save in the allele registry ID into our database instead of fetching it at runtime.

**Comment by kkrysiak** [comment]
That did seem to be the correct variant. I no longer see the issue. As far as implementation, that is definitely up to you. I can now access that URL (no hanging). So perhaps they had a temporary issue?

**Comment by kkrysiak** [comment]
Will be corrected by storing CAids for issue: https://github.com/griffithlab/civic-client/issues/879
