### ISSUE TITLE
generated AssertionSummaries.tsv is malformed

### ISSUE THREAD

**Issue by dandanxu** [griffithlab/civic-server#471]
Not sure where best to report this, hopefully this is the right place.

Whatever script is generating the AssertionSummaries.tsv files from https://civicdb.org/releases is introducing a new line in the middle of an assertion_description text block in the a VHL R167Q (c.500G>A) record.

![image](https://user-images.githubusercontent.com/4357327/50014525-3ab44180-ff92-11e8-9d86-45fe604ed47b.png)

The resulting TSV is malformed and can't be parsed properly by pandas and other CSV parsers.

**Comment by acoffman** [comment]
Hi @dandanxu thanks for the report! 

It looks like a Windows line break got into that summary text (probably due to a copy paste error). I have stripped the inadvertent whitespace and regenerated the nightly TSVS so they are corrected going forward. 

Furthermore, I have opened an issue here:  griffithlab/civic-client#1017 so that we can address the underlying issue going forward. 

Thanks again!
Adam
